from telemetry.telemetry import *

ALL_TOPICS = [
    BATTERY_VOLTAGE,
    ROBOT_STATE,
    ROBOT_DECISION,
    HAS_TARGET,
    ALIGNED,
    SHOOTER_READY,
    HAS_GAME_PIECE,
    MOVING,
    ENDGAME,
    SHOOTER_RPM_CURRENT,    
    SHOOTER_RPM_TARGET
]